steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/whybuy-platform:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/whybuy-platform:latest'
      - '.'
    timeout: 1200s

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/whybuy-platform:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/whybuy-platform:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'whybuy-platform'
      - '--image'
      - 'gcr.io/$PROJECT_ID/whybuy-platform:$COMMIT_SHA'
      - '--region'
      - 'us-central1'  # Change this to your preferred region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Remove this if you want authentication
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,PYTHONUNBUFFERED=1'
      - '--set-secrets'
      - 'SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_KEY=SUPABASE_KEY:latest,NEXT_PUBLIC_SUPABASE_URL=SUPABASE_URL:latest,NEXT_PUBLIC_SUPABASE_ANON_KEY=SUPABASE_KEY:latest'

# Timeout for the entire build
timeout: 1800s

# Options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/whybuy-platform:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/whybuy-platform:latest'
