steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/mittalhardik/tmrw-whybuy-supabase:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/mittalhardik/tmrw-whybuy-supabase:latest'
      - '--build-arg'
      - 'SUPABASE_URL=${_SUPABASE_URL}'
      - '--build-arg'
      - 'SUPABASE_KEY=${_SUPABASE_KEY}'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/github.com/mittalhardik/tmrw-whybuy-supabase:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/github.com/mittalhardik/tmrw-whybuy-supabase:latest'

substitutions:
  _SUPABASE_URL: ""
  _SUPABASE_KEY: ""
